
## Import library
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
#remove(list= ls())
library(DWLS)
library(Seurat)
source("runindi.R")

```

# Set env
```{r}
#Please check the environment on you PC
#python_env <- 'C:/Users/visitor01/.conda/envs/stged/python.exe'

#python_env <- 'D:/Users/tujia/anaconda3/envs/ccnet/python.exe'
#reticulate::use_python(python = python_env, required = TRUE)
library(reticulate)
use_condaenv("ccnet", required = TRUE)

```

# The code
```{r}

data_process <- function(sc_exp, sc_label, spot_exp, spot_loc,
                         gene_det_in_min_cells_per = 0.01, expression_threshold = 0,
                         nUMI = 100, verbose = FALSE, depthscale = 1e5, clean.only = TRUE) {
  # Ensure correct dimensions of inputs
  if(ncol(sc_exp) != length(sc_label)) {
    stop("Mismatch between number of cells in sc_exp and length of sc_label.")
  }
  if(ncol(spot_exp) != nrow(spot_loc)) {
    stop("Mismatch between number of spots in spot_exp and number of rows in spot_loc.")
  }
  
  # Process scRNA-seq data
  sc_matrix <- cleanCounts(sc_exp, gene_det_in_min_cells_per = gene_det_in_min_cells_per,
                           expression_threshold = expression_threshold, nUMI = nUMI,
                           verbose = verbose, depthscale = depthscale, clean.only = clean.only)
  sc_matrix <- as.matrix(sc_matrix)
  ind <- match(colnames(sc_matrix), colnames(sc_exp))
  sc_label <- sc_label[ind]
  
  # Process SRT data
  st_matrix <- cleanCounts(spot_exp, gene_det_in_min_cells_per = gene_det_in_min_cells_per,
                           expression_threshold = expression_threshold, nUMI = nUMI,
                           verbose = verbose, depthscale = depthscale, clean.only = clean.only)
  st_matrix <- as.matrix(st_matrix)
  ind_sp <- match(colnames(st_matrix), colnames(spot_exp))
  spot_loc <- spot_loc[ind_sp, ]
  
  # Find common genes between datasets
  com_gene <- intersect(rownames(sc_matrix), rownames(st_matrix))
  sc_exp <- sc_matrix[com_gene,]
  st_exp <- st_matrix[com_gene,]
  
  # Re-check and filter by nUMI counts
  index_sc <- colSums(sc_exp) >= nUMI
  sc_exp_filter <- sc_exp[, index_sc]
  sc_label_filter <- sc_label[index_sc]
  
  index_st <- colSums(st_exp) >= nUMI
  st_exp_filter <- st_exp[, index_st]
  spot_loc_filter <- spot_loc[index_st,]
  
  # Compile and return the database of cleaned data
  database <- list(sc_exp = sc_exp_filter, sc_label = sc_label_filter,
                   spot_exp = st_exp_filter, spot_loc = spot_loc_filter)
  return(database)
}


cleanCounts <- function(counts, gene_det_in_min_cells_per = 0.01, expression_threshold = 0,
                        nUMI = 100, verbose = FALSE, depthscale = 1, clean.only = FALSE) {
  
  if (!inherits(counts, "matrix")) stop("The 'counts' must be a matrix.")
  n = ncol(counts)
  if (verbose) message("Starting with ", n, " cells.")
  
  # Selecting genes detected in sufficient number of cells
  sufficient_cells = rowSums(counts > expression_threshold) > gene_det_in_min_cells_per * n
  counts = counts[sufficient_cells, ]
  
  # Filtering cells based on total UMI counts after gene filtering
  sufficient_umi = colSums(counts) > nUMI
  counts = counts[, sufficient_umi]
  
  if (clean.only) {
    if (verbose) message("Matrix filtered without scaling. Dimension: ", dim(counts))
    return(counts)
  } else {
    sf = colSums(counts) 
    scaled_counts = log(sweep(counts, 2, sf, FUN = "/") * depthscale + 1)
    if (verbose) message("Matrix scaled and log-transformed. Dimension: ", dim(scaled_counts))
    return(scaled_counts)
  }
}

```


# load code to generate spot data
```{r}

load( "../Realdata/SS_seqfish.Rdata")
source("../Sim_spt_data_without_normal.R")

ssfish  = sim_spt_count(SS_seqfish = SS_seqfish)

```



## the spots location information
```{r}

spot_loc <- ssfish$spot_data$spot_loc
spot_exp <- as.matrix(ssfish$spot_data$spot_exp)
rownames(spot_loc) <- colnames(spot_exp)
cell_type = colnames(ssfish$spot_data$spot_prop)
cell_type

```


# load the reference and spots data from here
```{r}

ssfish_ref <- readRDS("../Realdata/sim_fishplus.Rds")

sc_exp = ssfish_ref$sc_exp
sc_label = ssfish_ref$sc_lable
names(sc_label) <- colnames(sc_exp)

```


## check the cells in each spots
```{r}
spot_freq = ssfish$spot_data$truth_type_freq
colSums(spot_freq)

```

# check the results
```{r}

beta.type = ssfish$spot_data$spot_prop
celltype = colnames(beta.type)
celltype

```


# Load data
```{r}

datax = data_process(sc_exp = sc_exp,   sc_label = sc_label, 
                     spot_exp = spot_exp,  spot_loc = spot_loc,
                      gene_det_in_min_cells_per = 0.01, 
                     expression_threshold = 0,
                     nUMI =  100, verbose = FALSE, clean.only = TRUE)



```

## run DWLS
```{r}

dwls_res<- suppressWarnings(DWLS_run(datax, parallel = FALSE, 
                                     is_select_DEGs = FALSE, python_env))
dim(dwls_res)

saveRDS(dwls_res,"FISH_DWLS.RDS")

```

